#pragma once

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 768
#define MAX_SIMULATION_WIDTH (WINDOW_WIDTH + 2)
#define MAX_SIMULATION_HEIGHT (WINDOW_HEIGHT + 2)
#define SCALE_FACTOR_BASE 1.1
#define TPS 60
