#pragma once

#define SIMULATION_WIDTH 256
#define SIMULATION_HEIGHT 192
#define SCALE_FACTOR 4
#define WINDOW_WIDTH (SIMULATION_WIDTH * SCALE_FACTOR)
#define WINDOW_HEIGHT (SIMULATION_HEIGHT * SCALE_FACTOR)
#define TPS 60
