#pragma once

#define SIMULATION_WIDTH (SIMULATION_DISPLAYED_WIDTH + 2)
#define SIMULATION_HEIGHT (SIMULATION_DISPLAYED_HEIGHT + 2)
#define SIMULATION_DISPLAYED_X 1
#define SIMULATION_DISPLAYED_Y 1
#define SIMULATION_DISPLAYED_WIDTH 256
#define SIMULATION_DISPLAYED_HEIGHT 192
#define SCALE_FACTOR 4
#define WINDOW_WIDTH (SIMULATION_DISPLAYED_WIDTH * SCALE_FACTOR)
#define WINDOW_HEIGHT (SIMULATION_DISPLAYED_HEIGHT * SCALE_FACTOR)
#define TPS 60
